Update titles, pipeline images and tracking intro
objectiv/objectiv.io pull request #127
Opened 2021-11-17 14:56 UTC by jansenbob

* Update the pipeline images to better tell which part you're looking at in the docs
* Update the introduction of tracking to close the gap with other intros
* Update the titles of all introductions to provide a bit more information than **introduction** and make them discernable.

Todo: add a section that explains why we want you to map your application to the taxonomy in the Tracking section.

2021-11-17 15:15 UTC, ivarpruijn requested changes
Looks great! Just one very minor comment

2021-11-17 15:15 UTC, ivarpruijn commented on docs/docs/introduction.md
> +<img src={useBaseUrl('/img/objectiv-pipeline.svg')} alt="Objectiv Pipeline" class="img-l" />;
the `;` should be removed here

2021-11-18 09:25 UTC, jansenbob commented on docs/docs/introduction.md
> +<img src={useBaseUrl('/img/objectiv-pipeline.svg')} alt="Objectiv Pipeline" class="img-l" />;
done

2021-11-18 11:21 UTC, ivarpruijn approved these changes
Looks good

2021-11-18 11:35 UTC, jansenbob commented
minor bug: For contexts that have `ItemContext` as a parent or grandparent, `ItemContext` is not clickable.

So that includes:
InputContext
ActionContext
ButtonContext
LinkContext

The rest LGTM

2021-11-18 13:07 UTC, merged