Migrate docs to the React Tracker & upgrade to Docusaurus beta.21
objectiv/objectiv.io pull request #441
Opened 2022-06-01 19:23 UTC by ivarpruijn

2022-06-02 08:23 UTC, ivarpruijn commented on docs/docs/taxonomy/introduction.md
> +Each Event and Context type has its own [properties, requirements and relations](./reference/overview.md). These definitions are used to [validate the collected data and to debug the tracking instrum
Found after upgrading to beta.21, apparently broken link detection was changed.

2022-06-02 08:23 UTC, ivarpruijn commented on docs/src/components/join-slack-link/index.tsx
> -export default function JoinSlackLink({linkText='join us on Slack', trackingId='join-slack'}) {
we might revert to this, so the IDs don't change

2022-06-02 08:23 UTC, ivarpruijn commented on docs/src/css/custom.css
> +  color: transparent;
now needed to hide the textual label for these icons

2022-06-02 08:23 UTC, ivarpruijn commented on docs/src/theme/Navbar/MobileSidebar/Header/index.tsx
> +    </TrackedPressableContext>
Can now just be wrapped instead of ejected

2022-06-02 08:23 UTC, ivarpruijn commented on docs/src/theme/Navbar/MobileSidebar/Layout/index.tsx
> +    </TrackedOverlayContext>
Can now just be wrapped instead of ejected

2022-06-02 08:23 UTC, ivarpruijn commented on docs/src/theme/NavbarItem/NavbarNavLink.tsx
> +      {...props} />
Can now just be wrapped instead of ejected (with a little bit of extra logic above)

2022-06-02 08:23 UTC, ivarpruijn commented on docs/src/theme/PaginatorNavLink/index.tsx
> +    </TrackedLinkContext>
Can now just be wrapped instead of ejected

2022-06-02 08:23 UTC, ivarpruijn commented on docs/src/theme/TOC/index.tsx
> +    </TrackedNav>
Can now just be wrapped instead of ejected

2022-06-02 08:23 UTC, ivarpruijn commented on docs/src/theme/TOCItems/Tree.tsx
> +            href={`#${heading.id}`}
This is a new component that's a lot simpler than the now deleted `TOCItems`, but we still have to eject it to just replace the `<a>` with a `TrackedAnchor`.

2022-06-02 08:25 UTC, ivarpruijn commented on docs/src/theme/Logo/index.tsx
> +  return <TrackedLink Component={Logo} id={'logo'} href={logoLink} title={navbarTitle} {...props} />
Can now just be wrapped instead of ejected

2022-06-02 09:21 UTC, ivarpruijn commented on docs/src/theme/DocSidebarItem/Link/index.tsx
> +import { makeIdFromString } from '@objectiv/tracker-core';
Can remove this if we change default tracker behavior to always normalize

2022-06-02 09:21 UTC, ivarpruijn commented on docs/src/theme/Footer/LinkItem/index.tsx
> +    </TrackedLinkContext>
Can now just be wrapped instead of ejected

2022-06-02 09:21 UTC, ivarpruijn commented on docs/src/theme/Footer/LinkItem/index.tsx
> +import { makeIdFromString } from '@objectiv/tracker-core';
Can remove this if we change default tracker behavior to always normalize

2022-06-02 09:21 UTC, ivarpruijn commented on docs/src/theme/PaginatorNavLink/index.tsx
> +import { makeIdFromString } from '@objectiv/tracker-core';
Can remove this if we change default tracker behavior to always normalize

2022-06-02 09:31 UTC, ivarpruijn commented on docs/package.json
> +    "@objectiv/tracker-core": "^0.0.19",
Needed for `makeIdFromString` only; we might remove this if we change the default tracker behavior to normalize automatically.

2022-06-02 10:06 UTC, ivarpruijn commented on src/theme/Footer/Layout/index.tsx
>  import React, {ComponentProps} from 'react';
Aligned this site component to the new docs implementation

2022-06-02 10:06 UTC, ivarpruijn commented on src/theme/Footer/LinkItem/index.tsx
> +import { makeIdFromString } from '@objectiv/tracker-core';
Can remove this if we change default tracker behavior to always normalize

2022-06-02 10:28 UTC, ivarpruijn commented on docs/src/trackedComponents/trackedExpandableLi.tsx
> +import { makeIdFromString } from '@objectiv/tracker-core';
Can remove this if we change default tracker behavior to always normalize

2022-06-02 14:57 UTC, ivarpruijn commented on docs/src/components/join-slack-link/index.tsx
> -export default function JoinSlackLink({linkText='join us on Slack', trackingId='join-slack'}) {
Discussed with Vincent, we'll leave it like this

2022-06-02 15:02 UTC, ivarpruijn commented on docs/src/theme/DocSidebarItem/Category/index.tsx
> +import { makeIdFromString } from '@objectiv/tracker-core';
Can remove this if we change default tracker behavior to always normalize

2022-06-03 12:18 UTC, sdirosa requested changes
Some really small remarks, but overall this looks like a very nice cleanup!

In short:
- There are some location stack collision in FAQ and Get Help pages.
- No need to add the core tracker as dependency in package.json.
- Lots of duplicated components between website and docs, can we dedupe?

2022-06-03 12:18 UTC, sdirosa commented on docs/src/trackedComponents/TrackedLink.tsx
> +))
Improvement: we could share this (and other identical logic) between website and docs perhaps. For the future

2022-06-03 12:18 UTC, sdirosa commented on docs/docs/taxonomy/introduction.md
> +Each Event and Context type has its own [properties, requirements and relations](./reference/overview.md). These definitions are used to [validate the collected data and to debug the tracking instrum
Interesting. Perhaps the url-checker finally supports relative URLs?

2022-06-03 12:18 UTC, sdirosa commented on docs/package.json
> +    "@objectiv/tracker-core": "^0.0.19",
This is not necessary, tracker-core is a dependency of tracker-react. You can remove this line. 
I think this is more an IDE issue.

2022-06-03 12:18 UTC, sdirosa commented on docs/src/components/join-slack-link/index.tsx
>  };
Kinda related: I noticed that there are two links pointing to to Slack colliding both in the FAQ and the Get Help doc pages.
We probably need to wrap them in the correct Location Contexts.

2022-06-03 12:18 UTC, sdirosa commented on docs/src/theme/TOCItems/Tree.tsx
> +            href={`#${heading.id}`}
Very sad that the inner links are not Components and cannot be swizzled. Hopefully this will be improved in the future. I noticed that other themes do separate the TOC in multiple components correctly.

2022-06-03 12:18 UTC, sdirosa commented on src/theme/Footer/LinkItem/index.tsx
> +import useBaseUrl from "@docusaurus/useBaseUrl";
This component is identical between website and docs. Have we tried something to dedupe it, such as symlinking it?

Same goes for the Layout component and others.

2022-06-09 14:28 UTC, ivarpruijn commented on docs/package.json
> +    "@objectiv/tracker-core": "^0.0.19",
check done

2022-06-09 14:32 UTC, ivarpruijn commented on src/theme/Footer/LinkItem/index.tsx
> +import useBaseUrl from "@docusaurus/useBaseUrl";
I think we probably shouldn't introduce complexity with symlinks, and just merge the site & docs in the near future. No decision made yet, but I think we should first get these changes out and then consider if we can do a merge and how.

2022-06-10 08:14 UTC, sdirosa approved these changes

2022-06-10 09:41 UTC, merged